//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.NewSalesAward.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class CustomerCommitmentForm
    {
        public string FormOfCommitment { get; set; }
        public long RowID { get; set; }
    }
}
