//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.NewSalesAward.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class EditTabs_ProgramManagers
    {
        public int Status { get; set; }
        public int Type { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int RowID { get; set; }
        public Nullable<System.DateTime> RowCreateDT { get; set; }
        public string RowCreateUser { get; set; }
        public Nullable<System.DateTime> RowModifiedDT { get; set; }
        public string RowModifiedUser { get; set; }
        public string FullName { get; set; }
    }
}
