//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string name { get; set; }
        public string operator_code { get; set; }
        public string password { get; set; }
        public Nullable<int> serial_number { get; set; }
        public string epassword { get; set; }
        public Nullable<int> operatorlevel { get; set; }
        public string employee1 { get; set; }
        public byte[] npassword { get; set; }
        public string EmployeeID { get; set; }
    }
}
