//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTT.Model
{
    using System;
    
    public partial class PeakVolumeOfProgramsLaunching
    {
        public string Customer { get; set; }
        public Nullable<int> HalogenHeadLampPeakVolume { get; set; }
        public Nullable<int> LedHeadLampPeakVolume { get; set; }
        public Nullable<int> ConventionalTailLampPeakVolume { get; set; }
        public Nullable<int> LedTailLampPeakVolume { get; set; }
    }
}
