//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_CustomersWithProgramsLaunchingClosing2017
    {
        public long RowNumber { get; set; }
        public string Customer { get; set; }
        public string Region { get; set; }
    }
}
