//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTT.Model
{
    using System;
    
    public partial class usp_ST_SalesLeadLog_GetActivity_Result1
    {
        public string Customer { get; set; }
        public string Program { get; set; }
        public string Application { get; set; }
        public string SOP { get; set; }
        public Nullable<int> Volume { get; set; }
        public decimal SalesValue { get; set; }
        public string LastSalesActivity { get; set; }
        public int RowID { get; set; }
    }
}
