//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ST_LightingStudy_Hitlist_2016
    {
        public string Customer { get; set; }
        public string Program { get; set; }
        public Nullable<int> EstYearlySales { get; set; }
        public Nullable<int> PeakYearlyVolume { get; set; }
        public Nullable<int> SOPYear { get; set; }
        public string LED_Harness { get; set; }
        public string Application { get; set; }
        public string Region { get; set; }
        public string OEM { get; set; }
        public string NamePlate { get; set; }
        public string Component { get; set; }
        public string SOP { get; set; }
        public string EOP { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Volume2017 { get; set; }
        public Nullable<int> Volume2018 { get; set; }
        public Nullable<int> Volume2019 { get; set; }
        public Nullable<int> Volume2020 { get; set; }
        public Nullable<int> Volume2021 { get; set; }
        public Nullable<int> Volume2022 { get; set; }
        public string Status { get; set; }
        public Nullable<int> AwardedVolume { get; set; }
        public int ID { get; set; }
        public string SalesPerson { get; set; }
    }
}
