IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'EMPIRE\mcalix')
CREATE LOGIN [EMPIRE\mcalix] FROM WINDOWS
GO
CREATE USER [EMPIRE\mcalix] FOR LOGIN [EMPIRE\mcalix] WITH DEFAULT_SCHEMA=[EMPIRE\mcalix]
GO
REVOKE CONNECT TO [EMPIRE\mcalix]
