IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'EMPIREELECT\Mario')
CREATE LOGIN [EMPIREELECT\Mario] FROM WINDOWS
GO
CREATE USER [EMPIREELECT\Mario] FOR LOGIN [EMPIREELECT\Mario] WITH DEFAULT_SCHEMA=[EMPIREELECT\Mario]
GO
REVOKE CONNECT TO [EMPIREELECT\Mario]
