CREATE TABLE [CHR].[Variance]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[OriginPickupCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginPickupState] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinationDeliveryCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinationDeliveryState] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerReferenceNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerReferenceNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChrNumber] [bigint] NULL,
[ActualQuantity] [int] NULL,
[ActualPallets] [int] NULL,
[ActualWeight] [int] NULL,
[Hazardous] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Commodity] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PalletSpaces] [int] NULL,
[DriverHeavyWeightTix] [int] NULL,
[ActualPackagingCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeableWeight] [int] NULL,
[DriverLightWeightTix] [int] NULL,
[InnerPack] [int] NULL,
[DimensionalWeight] [int] NULL,
[OverDimensional] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FreightCharge] [decimal] (20, 6) NULL,
[TotalAccessorialsOtherCharges] [decimal] (20, 6) NULL,
[TotalCharges] [decimal] (20, 6) NULL,
[FuelSurcharge405] [decimal] (20, 6) NULL,
[TransferOfLoad740] [decimal] (20, 6) NULL,
[OrmOutOfRouteMiles] [int] NULL,
[InvoiceTotal] [decimal] (20, 6) NULL,
[Invoiced] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentComments] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndCustomerFreightCharge] [decimal] (20, 6) NULL,
[EndCustomerTotalAccessorialCharge] [decimal] (20, 6) NULL,
[EndCustomerTotalCharges] [decimal] (20, 6) NULL,
[BaselineCharge] [decimal] (20, 6) NULL,
[CarrierName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatorCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowCreateDT] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [CHR].[Variance] ADD CONSTRAINT [PK_Variance_1] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
