CREATE TABLE [CHR].[VarianceRawDataTemp]
(
[OriginPickupCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginPickupState] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinationDeliveryCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinationDeliveryState] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerReferenceNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerReferenceNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChrNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualQuantity] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualPallets] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualWeight] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hazardous] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Commodity] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PalletSpaces] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverHeavyWeightTix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualPackagingCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeableWeight] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverLightWeightTix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InnerPack] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimensionalWeight] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverDimensional] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FreightCharge] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalAccessorialsOtherCharges] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalCharges] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FuelSurcharge405] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransferOfLoad740] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrmOutOfRouteMiles] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceTotal] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoiced] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentComments] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndCustomerFreightCharge] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndCustomerTotalAccessorialCharge] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndCustomerTotalCharges] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaselineCharge] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
