CREATE TABLE [dbo].[raw_862_ship_sched]
(
[bss01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bss02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bss03] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bss04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bss05] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bss06] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bss08] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dock] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fst01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fst02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fst03] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fst04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin05] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linaa] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linab] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linac] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linad] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
