CREATE TABLE [dbo].[DistributedForeCast]
(
[Customer] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[base_part] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmpireSOP] [datetime] NULL,
[EmpireEOP] [datetime] NULL,
[CSMSOP] [datetime] NULL,
[CSMEOP] [datetime] NULL,
[Customerpart] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[empire_market_segment] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[empire_application] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssemblyPlant] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Program] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Badge] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NamePlate] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Jul09DistributedQty] [numeric] (38, 6) NULL,
[Jul09DistributedDollars] [numeric] (38, 6) NULL,
[Aug09DistributedQty] [numeric] (38, 6) NULL,
[Aug09DistributedDollars] [numeric] (38, 6) NULL,
[Sep09DistributedQty] [numeric] (38, 6) NULL,
[Sep09DistributedDollars] [numeric] (38, 6) NULL,
[Oct09DistributedQty] [numeric] (38, 6) NULL,
[Oct09DistributedDollars] [numeric] (38, 6) NULL,
[Nov09DistributedQty] [numeric] (38, 6) NULL,
[Nov09DistributedDollars] [numeric] (38, 6) NULL,
[Dec09DistributedQty] [numeric] (38, 6) NULL,
[Dec09DistributedDollars] [numeric] (38, 6) NULL,
[Jan10DistributedQty] [numeric] (38, 6) NULL,
[Jan10DistributedDollars] [numeric] (38, 6) NULL,
[Feb10DistributedQty] [numeric] (38, 6) NULL,
[Feb10DistributedDollars] [numeric] (38, 6) NULL,
[Mar10DistributedQty] [numeric] (38, 6) NULL,
[Mar10DistributedDollars] [numeric] (38, 6) NULL,
[Apr10DistributedQty] [numeric] (38, 6) NULL,
[Apr10DistributedDollars] [numeric] (38, 6) NULL,
[May10DistributedQty] [numeric] (38, 6) NULL,
[May10DistributedDollars] [numeric] (38, 6) NULL,
[Jun10DistributedQty] [numeric] (38, 6) NULL,
[Jun10DistributedDollars] [numeric] (38, 6) NULL,
[Jul10DistributedQty] [numeric] (38, 6) NULL,
[Jul10DistributedDollars] [numeric] (38, 6) NULL,
[Aug10DistributedQty] [numeric] (38, 6) NULL,
[Aug10DistributedDollars] [numeric] (38, 6) NULL,
[Sep10DistributedQty] [numeric] (38, 6) NULL,
[Sep10DistributedDollars] [numeric] (38, 6) NULL,
[Oct10DistributedQty] [numeric] (38, 6) NULL,
[Oct10DistributedDollars] [numeric] (38, 6) NULL,
[Nov10DistributedQty] [numeric] (38, 6) NULL,
[Nov10DistributedDollars] [numeric] (38, 6) NULL,
[Dec10DistributedQty] [numeric] (38, 6) NULL,
[Dec10DistributedDollars] [numeric] (38, 6) NULL,
[Jan11DistributedQty] [numeric] (38, 6) NULL,
[Jan11DistributedDollars] [numeric] (38, 6) NULL,
[Feb11DistributedQty] [numeric] (38, 6) NULL,
[Feb11DistributedDollars] [numeric] (38, 6) NULL,
[Mar11DistributedQty] [numeric] (38, 6) NULL,
[Mar11DistributedDollars] [numeric] (38, 6) NULL
) ON [PRIMARY]
GO
