CREATE TABLE [dbo].[FTRF_GlobalArrays]
(
[ID] [int] NOT NULL,
[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ArrayValues] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FTRF_GlobalArrays] ADD CONSTRAINT [PK__FTRF_GlobalArray__38EE7070] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
