CREATE TABLE [dbo].[freight_pfa_copy]
(
[pfa_id] [int] NOT NULL,
[pfa_date] [datetime] NULL,
[pfa_status] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[requestor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[approver] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[content_paretto] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[part_description] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qty_uom] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[est_weight] [decimal] (18, 6) NULL,
[weight_uom] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[in_house_due_date] [datetime] NULL,
[cml_item] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cml_date] [datetime] NULL,
[fg_customer_paretto] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fg_where_used] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[empire_company] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reason_paretto] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_po] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_carrier] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_mode] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_account_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_chareback] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_carrier] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_mode] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_account_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[override] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[override_reason] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[override_approver] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qi_number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[attachment_link] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[root_cause] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[corrective_action] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preventive_action] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_paretto] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_street_address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_city] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_province] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_zip_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_contact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_contact_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_paretto] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_street_address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_city] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_state] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_province] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_zip_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_contact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_contact_phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carrier] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mode] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account_number] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[est_cost] [decimal] (18, 6) NULL,
[tracking_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[freight_pfa_copy] ADD CONSTRAINT [freight_pfa_x] PRIMARY KEY CLUSTERED  ([pfa_id]) ON [PRIMARY]
GO
