CREATE TABLE [dbo].[FTRF_Modules]
(
[ID] [int] NOT NULL,
[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Settings] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FTRF_Modules] ADD CONSTRAINT [PK__FTRF_Modules__53A266AC] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
