CREATE TABLE [dbo].[EEH_part_standard]
(
[Time_stamp] [datetime] NOT NULL,
[Fiscal_year] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Period] [smallint] NULL,
[Reason] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[part] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[price] [numeric] (20, 6) NULL,
[cost] [numeric] (20, 6) NULL,
[account_number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[material] [numeric] (20, 6) NULL,
[labor] [numeric] (20, 6) NULL,
[burden] [numeric] (20, 6) NULL,
[other] [numeric] (20, 6) NULL,
[cost_cum] [numeric] (20, 6) NULL,
[material_cum] [numeric] (20, 6) NULL,
[burden_cum] [numeric] (20, 6) NULL,
[other_cum] [numeric] (20, 6) NULL,
[labor_cum] [numeric] (20, 6) NULL,
[flag] [int] NULL,
[premium] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qtd_cost] [numeric] (20, 6) NULL,
[qtd_material] [numeric] (20, 6) NULL,
[qtd_labor] [numeric] (20, 6) NULL,
[qtd_burden] [numeric] (20, 6) NULL,
[qtd_other] [numeric] (20, 6) NULL,
[qtd_cost_cum] [numeric] (20, 6) NULL,
[qtd_material_cum] [numeric] (20, 6) NULL,
[qtd_labor_cum] [numeric] (20, 6) NULL,
[qtd_burden_cum] [numeric] (20, 6) NULL,
[qtd_other_cum] [numeric] (20, 6) NULL,
[planned_cost] [numeric] (20, 6) NULL,
[planned_material] [numeric] (20, 6) NULL,
[planned_labor] [numeric] (20, 6) NULL,
[planned_burden] [numeric] (20, 6) NULL,
[planned_other] [numeric] (20, 6) NULL,
[planned_cost_cum] [numeric] (20, 6) NULL,
[planned_material_cum] [numeric] (20, 6) NULL,
[planned_labor_cum] [numeric] (20, 6) NULL,
[planned_burden_cum] [numeric] (20, 6) NULL,
[planned_other_cum] [numeric] (20, 6) NULL,
[frozen_cost] [numeric] (20, 6) NULL,
[frozen_material] [numeric] (20, 6) NULL,
[frozen_burden] [numeric] (20, 6) NULL,
[frozen_labor] [numeric] (20, 6) NULL,
[frozen_other] [numeric] (20, 6) NULL,
[frozen_cost_cum] [numeric] (20, 6) NULL,
[frozen_material_cum] [numeric] (20, 6) NULL,
[frozen_burden_cum] [numeric] (20, 6) NULL,
[frozen_labor_cum] [numeric] (20, 6) NULL,
[frozen_other_cum] [numeric] (20, 6) NULL,
[cost_changed_date] [datetime] NULL,
[qtd_changed_date] [datetime] NULL,
[planned_changed_date] [datetime] NULL,
[frozen_changed_date] [datetime] NULL,
[LastUser] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastChangeOfCost] [datetime] NULL
) ON [PRIMARY]
GO
