CREATE TABLE [dbo].[edi_830_shp]
(
[bfr_01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_03] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_05] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_06] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_07] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_08] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_09] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_10] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_11] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n1_01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n1_02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n1_03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n1_04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_03] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_05] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_06] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_07] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_08] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin_09] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp_01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp_02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp_03] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp_04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp_05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rff_01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rff_02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
