CREATE TABLE [dbo].[TargetPreResults2]
(
[CalculatedABC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitCost] [numeric] (10, 6) NULL,
[BasePart] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOP] [datetime] NULL,
[EOP] [datetime] NULL,
[PartPhase] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentMinDays] [numeric] (10, 2) NULL,
[CurrentMaxDays] [numeric] (10, 2) NULL,
[CurrentInventory] [int] NULL,
[CurrentInventoryCost] [int] NULL,
[CurrentMinQty] [int] NULL,
[CurrentMaxQty] [int] NULL,
[CurrentMinCost] [int] NULL,
[CurrentMaxCost] [int] NULL,
[CurrentMinQtyVariance] [int] NULL,
[CurrentMaxQtyVariance] [int] NULL,
[CurrentMinCostVariance] [int] NULL,
[CurrentMaxCostVariance] [int] NULL,
[AvgDailyDemand] [int] NULL,
[WeekDate0] [datetime] NULL,
[Week0Balance] [int] NULL,
[MinDays0] [int] NULL,
[MaxDays0] [int] NULL,
[Week0MinVariance] [int] NULL,
[Week0MaxVariance] [int] NULL,
[WeekDate1] [datetime] NULL,
[Week1Balance] [int] NULL,
[MinDays1] [numeric] (6, 2) NULL,
[MaxDays1] [numeric] (6, 2) NULL,
[Week1MinVariance] [numeric] (18, 2) NULL,
[Week1MaxVariance] [numeric] (18, 2) NULL,
[WeekDate2] [datetime] NULL,
[Week2Balance] [int] NULL,
[MinDays2] [numeric] (6, 2) NULL,
[MaxDays2] [numeric] (6, 2) NULL,
[Week2MinVariance] [numeric] (18, 2) NULL,
[Week2MaxVariance] [numeric] (18, 2) NULL,
[WeekDate3] [datetime] NULL,
[Week3Balance] [int] NULL,
[MinDays3] [numeric] (6, 2) NULL,
[MaxDays3] [numeric] (6, 2) NULL,
[Week3MinVariance] [numeric] (18, 2) NULL,
[Week3MaxVariance] [numeric] (18, 2) NULL,
[WeekDate4] [datetime] NULL,
[Week4Balance] [int] NULL,
[MinDays4] [numeric] (6, 2) NULL,
[MaxDays4] [numeric] (6, 2) NULL,
[Week4MinVariance] [numeric] (18, 2) NULL,
[Week4MaxVariance] [numeric] (18, 2) NULL,
[WeekDate5] [datetime] NULL,
[Week5Balance] [int] NULL,
[MinDays5] [numeric] (6, 2) NULL,
[MaxDays5] [numeric] (6, 2) NULL,
[Week5MinVariance] [numeric] (18, 2) NULL,
[Week5MaxVariance] [numeric] (18, 2) NULL,
[Week5MaxVarianceCost] [numeric] (29, 8) NULL,
[WeekDate6] [datetime] NULL,
[Week6Balance] [int] NULL,
[MinDays6] [numeric] (6, 2) NULL,
[MaxDays6] [numeric] (6, 2) NULL,
[Week6MinVariance] [numeric] (18, 2) NULL,
[Week6MaxVariance] [numeric] (18, 2) NULL,
[WeekDate7] [datetime] NULL,
[Week7Balance] [int] NULL,
[MinDays7] [numeric] (6, 2) NULL,
[MaxDays7] [numeric] (6, 2) NULL,
[Week7MinVariance] [numeric] (18, 2) NULL,
[Week7MaxVariance] [numeric] (18, 2) NULL,
[WeekDate8] [datetime] NULL,
[Week8Balance] [int] NULL,
[MinDays8] [numeric] (6, 2) NULL,
[MaxDays8] [numeric] (6, 2) NULL,
[Week8MinVariance] [numeric] (18, 2) NULL,
[Week8MaxVariance] [numeric] (18, 2) NULL,
[WeekDate9] [datetime] NULL,
[Week9Balance] [int] NULL,
[MinDays9] [numeric] (6, 2) NULL,
[MaxDays9] [numeric] (6, 2) NULL,
[Week9MinVariance] [numeric] (18, 2) NULL,
[Week9MaxVariance] [numeric] (18, 2) NULL,
[WeekDate10] [datetime] NULL,
[Week10Balance] [int] NULL,
[MinDays10] [numeric] (6, 2) NULL,
[MaxDays10] [numeric] (6, 2) NULL,
[Week10MinVariance] [numeric] (18, 2) NULL,
[Week10MaxVariance] [numeric] (18, 2) NULL,
[Week10MaxVarianceCost] [numeric] (29, 8) NULL,
[WeekDate11] [datetime] NULL,
[Week11Balance] [int] NULL,
[MinDays11] [numeric] (6, 2) NULL,
[MaxDays11] [numeric] (6, 2) NULL,
[Week11MinVariance] [numeric] (18, 2) NULL,
[Week11MaxVariance] [numeric] (18, 2) NULL,
[WeekDate12] [datetime] NULL,
[Week12Balance] [int] NULL,
[MinDays12] [numeric] (6, 2) NULL,
[MaxDays12] [numeric] (6, 2) NULL,
[Week12MinVariance] [numeric] (18, 2) NULL,
[Week12MaxVariance] [numeric] (18, 2) NULL,
[WeekDate13] [datetime] NULL,
[Week13Balance] [int] NULL,
[MinDays13] [numeric] (6, 2) NULL,
[MaxDays13] [numeric] (6, 2) NULL,
[Week13MinVariance] [numeric] (18, 2) NULL,
[Week13MaxVariance] [numeric] (18, 2) NULL,
[WeekDate14] [datetime] NULL,
[Week14Balance] [int] NULL,
[MinDays14] [numeric] (6, 2) NULL,
[MaxDays14] [numeric] (6, 2) NULL,
[Week14MinVariance] [numeric] (18, 2) NULL,
[Week14MaxVariance] [numeric] (18, 2) NULL,
[WeekDate15] [datetime] NULL,
[Week15Balance] [int] NULL,
[MinDays15] [numeric] (6, 2) NULL,
[MaxDays15] [numeric] (6, 2) NULL,
[Week15MinVariance] [numeric] (18, 2) NULL,
[Week15MaxVariance] [numeric] (18, 2) NULL,
[WeekDate16] [datetime] NULL,
[Week16Balance] [int] NULL,
[MinDays16] [numeric] (6, 2) NULL,
[MaxDays16] [numeric] (6, 2) NULL,
[Week16MinVariance] [numeric] (18, 2) NULL,
[Week16MaxVariance] [numeric] (18, 2) NULL,
[Scheduler] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
