CREATE TABLE [dbo].[raw_830_auth_copy]
(
[bfr_rel] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_sched_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_sched_qty_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_start_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_end_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_gen_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_po] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ath01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ath02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ath03] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ath04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ath05] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin05] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linaa] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linab] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linac] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linad] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fab_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fab_end_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fab_qty] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[raw_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[raw_end_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[raw_qty] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pq_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pq_end_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pq_qty] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
