CREATE TABLE [dbo].[FTRF_UserArrays]
(
[ID] [int] NOT NULL,
[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ArrayValues] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FTRF_UserArrays] ADD CONSTRAINT [PK__FTRF_UserArrays__10AB74EC] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
