CREATE TABLE [dbo].[raw_830_shp]
(
[bfr_rel] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_sched_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_sched_qty_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_start_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bss02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_gen_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bfr_po] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n101_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n104_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[auth_to_ship_qty] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_ship_qty] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_ship_date] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_shipper_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf9] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf10] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[udf7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lin05] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linaa] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linab] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linac] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[linad] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp01] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp02] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp03] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp04] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
