CREATE TABLE [dbo].[CSMAdj]
(
[Release_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Version] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Core Nameplate Region Mnemonic] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Core Nameplate Plant Mnemonic] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mnemonic-Vehicle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mnemonic-Vehicle Plant] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mnemonic-Platform] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Region] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Market] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plant] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plant State Province] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Plant] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Plant Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source Plant Region] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Design Parent] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Engineering Group] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manufacturing Group] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Manufacturer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Parent] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Brand] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Platform Design Owner] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Architecture] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Platform] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nameplate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EOP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lifecycle (Time)] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Assembly Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Strategic Group] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales Group] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Global Nameplate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Design Center] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Design Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary Design Region] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary Design Center] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary Design Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary Design Region] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GVW Rating] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GVW Class] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Car Truck] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Production Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Global Production Segment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Regional Sales Segment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Global Production Price Class] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Global Sales Segment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Global Sales Sub-Segment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Global Sales Price Class] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Short Term Risk Rating] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Long Term Risk Rating] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-00] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-01] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-02] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-08] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-09] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jan-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Feb-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mar-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Apr-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[May-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jun-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jul-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aug-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sep-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Oct-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nov-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dec-19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2008] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2008] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2008] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2008] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2009] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2009] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2009] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2009] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2010] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2010] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2010] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2010] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2011] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2011] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2011] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2011] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2012] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2012] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2012] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2012] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2013] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2013] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2013] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2013] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2014] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2014] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2014] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2014] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2015] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2015] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2015] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2015] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2016] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2016] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2016] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2016] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2017] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2017] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2017] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2017] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2018] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2018] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2018] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2018] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2019] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2019] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2019] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2019] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2020] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2020] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2020] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2020] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2021] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2021] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2021] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2021] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2022] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2022] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2022] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2022] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2023] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2023] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2023] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2023] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q1 2024] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q2 2024] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q3 2024] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Q4 2024] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2000] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2001] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2002] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2003] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2004] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2005] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2006] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2007] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2008] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2009] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2010] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2011] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2012] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2013] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2014] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2015] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2016] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2017] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2018] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2019] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2020] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2021] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2022] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2023] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CY 2024] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
