CREATE TABLE [dbo].[FTRF_RFGunArrayValues]
(
[ID] [int] NOT NULL,
[RFGunID] [int] NOT NULL,
[ArrayID] [int] NOT NULL,
[ArrayValues] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FTRF_RFGunArrayValues] ADD CONSTRAINT [PK__FTRF_RFGunArrayV__42ACE4D4] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
