CREATE TABLE [EDIPILOT].[Invoice210Detail]
(
[Status] [int] NOT NULL CONSTRAINT [DF__Invoice21__Statu__1F1FE22E] DEFAULT ((0)),
[Type] [int] NOT NULL CONSTRAINT [DF__Invoice210__Type__20140667] DEFAULT ((0)),
[RawDocumentGUID] [uniqueidentifier] NULL,
[InvoiceNumber] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[b3lXAssignedNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n9Qualifier] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[n9Data] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[podDate] [datetime] NULL,
[podTime] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[podName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l5LadingLineItemNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l5LadingDescription] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L0LadinglineItemNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l0BilledQty] [numeric] (20, 6) NULL,
[l0BilledQtyUOM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l0WeightQualfier] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l0Volume] [numeric] (20, 6) NULL,
[l0VolumeUnit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l0LadingQty] [numeric] (20, 6) NULL,
[l0PackagingCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l1ladingLineItem] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l1FreightRate] [numeric] (20, 6) NULL,
[l1RateQualifier] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l1RateCharge] [numeric] (20, 6) NULL,
[L4Length] [numeric] (20, 6) NULL,
[L4Width] [numeric] (20, 6) NULL,
[L4Height] [numeric] (20, 6) NULL,
[L4UOM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4Qty] [numeric] (20, 6) NULL,
[UserDefined1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined8] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined9] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserDefined10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowID] [int] NOT NULL IDENTITY(1, 1),
[RowCreateDT] [datetime] NULL CONSTRAINT [DF__Invoice21__RowCr__21082AA0] DEFAULT (getdate()),
[RowCreateUser] [sys].[sysname] NOT NULL CONSTRAINT [DF__Invoice21__RowCr__21FC4ED9] DEFAULT (user_name()),
[RowModifiedDT] [datetime] NULL CONSTRAINT [DF__Invoice21__RowMo__22F07312] DEFAULT (getdate()),
[RowModifiedUser] [sys].[sysname] NOT NULL CONSTRAINT [DF__Invoice21__RowMo__23E4974B] DEFAULT (user_name())
) ON [PRIMARY]
GO
ALTER TABLE [EDIPILOT].[Invoice210Detail] ADD CONSTRAINT [PK__Invoice2__FFEE745011C5E710] PRIMARY KEY NONCLUSTERED  ([RowID]) ON [PRIMARY]
GO
