CREATE TABLE [EEIACCT].[ServiceDemandForecast]
(
[Base Part] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Part Number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROGRAM] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Application] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EAU For Production] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Production Price] [money] NULL,
[Service Price] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Minimum Buy] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Production EOP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Empire Service commitment in Years] [int] NULL,
[End Of Service Date For Empire] [int] NULL,
[Year in which price can be increased] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Min Order Qty] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping @ Service Price (Yes/No)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of 1st shipment @ Service Price] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Scheduler] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active Yes/No (2011)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active Yes/No (2012)] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vlookup-Pricing Service List] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Service shipment for 2010 after EOP] [int] NULL,
[2011 Service shipments] [int] NULL,
[Current Demand for 2011] [int] NULL,
[Inventory on Hand (Current)] [int] NULL,
[2012 Service shipments] [int] NULL,
[Current 2012 Demand] [int] NULL,
[Comments] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Additional Comments] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service demand prior to 2010] [int] NULL,
[2010 Service] [int] NULL,
[2011 Service] [int] NULL,
[2012 Service] [int] NULL,
[2013 Service] [int] NULL,
[2014 Service] [int] NULL,
[2015 Service] [int] NULL,
[2016 Service] [int] NULL,
[2017 Service] [int] NULL,
[2018 Service] [int] NULL,
[2019 Service] [int] NULL,
[2020 Service] [int] NULL,
[2021 Service] [int] NULL,
[2022 Service] [int] NULL,
[2023 Service] [int] NULL,
[2024 Service] [int] NULL,
[2025 Service] [int] NULL,
[Total Service Cum starting 2010 until end of commitment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
