CREATE TABLE [EEIUser].[QT_Test]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [EEIUser].[QT_Test] ADD CONSTRAINT [PK__QT_Test__3214EC271A7AC93D] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
