CREATE TABLE [EEIUser].[QT_QuoteLog2007]
(
[Quote#] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Receipt Date] [datetime2] NULL,
[Customer] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cust  Req'd Date] [datetime2] NULL,
[Due Date] [datetime2] NULL,
[Customer P/N] [int] NULL,
[EEI P/N] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requote] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes / Changes / Additional quote volumes] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EAU] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Application] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[End User] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Model Year] [float] NULL,
[Sales] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PM] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eng] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer RFQ#] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[App Code] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTA %] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTA YRS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REV] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nameplate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Issues / Problems] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Engineering Intials] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Engineering Date] [datetime2] NULL,
[Materials Intials] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Materials Date] [datetime2] NULL,
[Quote Review Intials] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quote Review Date] [datetime2] NULL,
[Quote Pricing Intials] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quote Pricing Date] [datetime2] NULL,
[Customer Quote Intials] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Quote Date] [datetime2] NULL,
[Quoted Price] [money] NULL,
[Total Quoted Sales] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New Business Awarded] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quote Status] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NoName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
