CREATE TABLE [EEIUser].[ST_LightingStudy_Unbooked]
(
[Customer] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerRegion] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOP] [datetime2] NULL,
[EOP] [datetime2] NULL,
[ShortTermRisk] [int] NULL,
[LongTermRisk] [int] NULL,
[GlobalSalesSegment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GlobalSalesSubSegment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GlobalProductionSegment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarTruck] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampLowBeamType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FblFitment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampAdaptiveFunctionDbl] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampAdaptiveFunctionAfs] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampAdaptiveFunctionAdb] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampLowHighBeamBulbCount] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampAdaptiveFunctionAhb] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampHighBeamType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FblLocation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampAdbActuationType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampPowerConsumptionWatts] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraFitment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraLightingFunctions] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CameraUnits] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MotorFitment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MotorUnits] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrontIndicatorType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrlFitment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrlImplementation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrlType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrontFogFitment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FrontFogType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionPlant] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DesignParent] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManufacturerGroup] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Region] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LedHeadlampCategory] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TailLampLightSourceType] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TailLampLightSourceCategory] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TailLampUnits] [int] NULL,
[VehicleUnits] [int] NULL,
[Group] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Component] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForecastDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MnemonicVehicle] [int] NULL,
[MnemonicVehiclePlant] [int] NULL,
[SalesParent] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionBrand] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManufacturerParent] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductionNameplate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Platform] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HeadlampUnits] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComponentVolume2014] [int] NULL,
[ComponentVolume2015] [int] NULL,
[ComponentVolume2016] [int] NULL,
[ComponentVolume2017] [int] NULL,
[ComponentVolume2018] [int] NULL,
[ComponentVolume2019] [int] NULL,
[ComponentVolume2020] [int] NULL,
[ComponentVolume2021] [int] NULL,
[VehicleVolume2014] [int] NULL,
[VehicleVolume2015] [int] NULL,
[VehicleVolume2016] [int] NULL,
[VehicleVolume2017] [int] NULL,
[VehicleVolume2018] [int] NULL,
[VehicleVolume2019] [int] NULL,
[VehicleVolume2020] [int] NULL,
[VehicleVolume2021] [int] NULL,
[VehiclePlantLatitude] [float] NULL,
[VehiclePlantLongitude] [float] NULL
) ON [PRIMARY]
GO
