CREATE TABLE [EEIUser].[acctg_csm_tail_lamp]
(
[Component] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Service] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: Region] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: Manufacturer Group] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: Production Brand] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: Production Nameplate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: Platform] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: Program] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: SOP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: EOP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VP: Global Sales Segment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Light Source Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Light Source Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Modularity] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Supplier Group] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Supplier] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Supplier Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Supplier Region] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Supplier Plant] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tail Lamp Units] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle Units] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Component Volume 2017] [float] NULL,
[Component Volume 2018] [float] NULL,
[Component Volume 2019] [float] NULL,
[Component Volume 2020] [float] NULL,
[Component Volume 2021] [float] NULL,
[Component Volume 2022] [float] NULL,
[Component Volume 2023] [float] NULL,
[Component Volume 2024] [float] NULL,
[Vehicle Volume 2017] [float] NULL,
[Vehicle Volume 2018] [float] NULL,
[Vehicle Volume 2019] [float] NULL,
[Vehicle Volume 2020] [float] NULL,
[Vehicle Volume 2021] [float] NULL,
[Vehicle Volume 2022] [float] NULL,
[Vehicle Volume 2023] [float] NULL,
[Vehicle Volume 2024] [float] NULL
) ON [PRIMARY]
GO
