CREATE TABLE [EEIUser].[acctg_csm_study_BRAKE_LIGHTING]
(
[FORECAST_ID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VERSION] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MNEMONIC] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMPONENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAMP_TYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPPLIER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UNITS] [int] NULL,
[FOOTNOTE] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [EEIUser].[acctg_csm_study_BRAKE_LIGHTING] ADD CONSTRAINT [PK_acctg_csm_FORWARD_LIGHTING] PRIMARY KEY CLUSTERED  ([FORECAST_ID], [VERSION], [MNEMONIC], [SUPPLIER]) ON [PRIMARY]
GO
