CREATE TABLE [EEIUser].[acctg_sales_newsales]
(
[Sales_ID] [int] NOT NULL,
[Customer Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Empire Part Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Replacing Empire Part Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Part Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle Platform] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Application] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qty Per vehicle] [float] NULL,
[Take rate %] [float] NULL,
[Family Allocation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSM EAU ] [datetime] NULL,
[Quote Date] [datetime] NULL,
[Quote Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quoted EAU                    ] [float] NULL,
[MOQ Requirement] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quoted Selling Price] [money] NULL,
[Quoted Annual Sales] [money] NULL,
[Quoted LTA Commitment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Production PO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Production PO#] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Alternative Customer Commitment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PO Selling Price] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOP Date] [datetime] NULL,
[EOP Date] [datetime] NULL,
[Quote vs# PO Selling Price Variance] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Tooling PO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount of Tooling PO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTA] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Crimp die PO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amortization (Yes / No)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing Trigger and Installments] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tooling Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Budget Capex ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Empire Facility (Troy, ELP, AL)] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Freight Terms] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F36] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F37] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F38] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F39] [float] NULL,
[F40] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F41] [float] NULL,
[F42] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F43] [float] NULL,
[F44] [datetime] NULL,
[F45] [float] NULL,
[F46] [float] NULL,
[F47] [float] NULL,
[F48] [money] NULL,
[F49] [money] NULL,
[F50] [float] NULL,
[F51] [datetime] NULL,
[F52] [money] NULL,
[F53] [money] NULL,
[F54] [money] NULL,
[F55] [datetime] NULL,
[F56] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [EEIUser].[acctg_sales_newsales] ADD CONSTRAINT [PK_NewSales1] PRIMARY KEY CLUSTERED  ([Sales_ID]) ON [PRIMARY]
GO
