CREATE TABLE [FedEx].[Variance]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[BillToAccountNumber] [bigint] NULL,
[InvoiceDate] [datetime] NULL,
[InvoiceNumber] [bigint] NULL,
[StoreId] [int] NULL,
[OriginalAmountDue] [decimal] (12, 6) NULL,
[CurrentBalance] [decimal] (12, 6) NULL,
[Payor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroundTrackingIdPrefix] [int] NULL,
[ExpressOrGroundTrackingId] [bigint] NOT NULL,
[TransportationChargeAmount] [decimal] (12, 6) NULL,
[NetChargeAmount] [decimal] (12, 6) NULL,
[ServiceType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroundService] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentDate] [datetime] NULL,
[PodDeliveryDate] [datetime] NULL,
[PodServiceAreaCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PodSignatureDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualWeightAmount] [decimal] (12, 6) NULL,
[ActualWeightUnits] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RatedWeightAmount] [decimal] (12, 6) NULL,
[RatedWeightUnits] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfPieces] [int] NULL,
[BundleNumber] [int] NULL,
[MeterNumber] [bigint] NULL,
[TdMasterTrackingId] [bigint] NULL,
[ServicePackaging] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimLength] [int] NULL,
[DimWidth] [int] NULL,
[DimHeight] [int] NULL,
[DimDivisor] [int] NULL,
[DimUnit] [int] NULL,
[RecipientName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientCompany] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientAddressLine1] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientAddressLine2] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientCountry] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperCompany] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperAddressLine1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperAddressLine2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperCountry] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalCustomerReference] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalRefNumber2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalRefNumber3PoNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalDepartmentReferenceDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedCustomerReference] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedRefNumber2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedRefNumber3PoNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedDepartmentReferenceDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RmaNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalRecipientAddressLine1] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalRecipientAddressLine2] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalRecipientCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalRecipientState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalRecipientZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalRecipientCountry] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZoneCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CostAllocation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlternateAddressLine1] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlternateAddressLine2] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlternateCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlternateStateProvince] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlternateZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlternateCountryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrossRefTrackingIdPrefix] [int] NULL,
[CrossRefTrackingId] [bigint] NULL,
[EntryDate] [datetime] NULL,
[EntryNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomsValue] [decimal] (12, 6) NULL,
[CustomsValueCurrencyCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeclaredValue] [decimal] (12, 6) NULL,
[DeclaredValueCurrencyCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityDescription1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityCountryCode1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityDescription2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityCountryCode2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityDescription3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityCountryCode3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityDescription4] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityCountryCode4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyConversionDate] [datetime] NULL,
[CurrencyConversionRate] [decimal] (12, 6) NULL,
[MultiweightNumber] [int] NULL,
[MultiweightTotalUnits] [int] NULL,
[MultiweightTotalWeight] [int] NULL,
[MultiweightTotalShipmentChargeAmount] [decimal] (12, 6) NULL,
[MultiweightTotalShipmentWeight] [int] NULL,
[GroundTrackingIdAddressCorrectionDiscountChargeAmount] [decimal] (12, 6) NULL,
[GroundTrackingIdAddressCorrectionGrossChargeAmount] [decimal] (12, 6) NULL,
[RatedMethod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SortHub] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstimatedWeight] [int] NULL,
[EstimatedWeightUnit] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalClass] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessCategory] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageSize] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeliveryConfirmation] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TenderedDate] [datetime] NULL,
[TrackingIdChargeDescription1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription3] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription4] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription5] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription6] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription7] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription8] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount8] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription9] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount9] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription10] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription11] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription12] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription13] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription14] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription15] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription16] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount16] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription17] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount17] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription18] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount18] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription19] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount19] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription20] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount20] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription21] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount21] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription22] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount22] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription23] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount23] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription24] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount24] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeDescription25] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackingIdChargeAmount25] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentNotes] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NormalizedWeightRounded] [decimal] (27, 0) NULL,
[OperatorCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowCreateDT] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [FedEx].[Variance] ADD CONSTRAINT [PK_Variance] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
