CREATE TABLE [FT].[BOM]
(
[BOMID] [int] NOT NULL,
[ParentPart] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChildPart] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StdQty] [numeric] (20, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [FT].[BOM] ADD CONSTRAINT [PK__BOM__7D541716] PRIMARY KEY CLUSTERED  ([BOMID]) ON [PRIMARY]
GO
ALTER TABLE [FT].[BOM] ADD CONSTRAINT [UQ__BOM__7E483B4F] UNIQUE NONCLUSTERED  ([ParentPart], [ChildPart]) ON [PRIMARY]
GO
