CREATE TABLE [FT].[ProTransASN_RawData]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[FileName] [sys].[sysname] NOT NULL,
[Contents] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [tinyint] NOT NULL CONSTRAINT [DF__ProTransA__Statu__09F5EC6A] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [FT].[ProTransASN_RawData] ADD CONSTRAINT [PK__ProTransASN_RawD__080DA3F8] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [FT].[ProTransASN_RawData] ADD CONSTRAINT [UQ__ProTransASN_RawD__0901C831] UNIQUE NONCLUSTERED  ([FileName]) ON [PRIMARY]
GO
