CREATE TABLE [FT].[UOP_FileLog]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[FileName] [sys].[sysname] NOT NULL,
[Message] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [int] NULL CONSTRAINT [DF__UOP_FileL__Statu__695412AE] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [FT].[UOP_FileLog] ADD CONSTRAINT [PK__UOP_FileLog__685FEE75] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
