CREATE TABLE [UPS].[Variance]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Version] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecipientNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceDate] [datetime] NULL,
[InvoiceNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceTypeCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceTypeDetailCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountTaxId] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceCurrencyCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceAmount] [decimal] (20, 6) NULL,
[TransactionDate] [datetime] NULL,
[PickupRecordNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadShipmentNumber] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorldEaseNumber] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentReferenceNumber1] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentReferenceNumber2] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillOptionCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageQuantity] [decimal] (20, 6) NULL,
[OversizeQuantity] [decimal] (20, 6) NULL,
[TrackingNumber] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageReferenceNumber1] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageReferenceNumber2] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageReferenceNumber3] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageReferenceNumber4] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageReferenceNumber5] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnteredWeight] [decimal] (20, 6) NULL,
[EnteredWeightUnitOfMeasure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilledWeight] [decimal] (20, 6) NULL,
[BilledWeightUnitOfMeasure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContainerType] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilledWeightType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageDimensions] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zone] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeCategoryCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeCategoryDetailCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeSource] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeCode1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeDetailCode1] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeDetailValue1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeCode2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeDetailCode2] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeDetailValue2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeClassificationCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeDescriptionCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargeDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChargedUnitQuantity] [decimal] (20, 6) NULL,
[BasisCurrencyCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BasisValue] [decimal] (20, 6) NULL,
[TaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionCurrencyCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncentiveAmount] [decimal] (20, 6) NULL,
[NetAmount] [decimal] (20, 6) NULL,
[MiscellaneousCurrencyCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousIncentiveAmount] [decimal] (20, 6) NULL,
[MiscellaneousNetAmount] [decimal] (20, 6) NULL,
[AlternateInvoicingCurrencyCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlternateInvoiceAmount] [decimal] (20, 6) NULL,
[InvoiceExchangeRate] [decimal] (20, 6) NULL,
[TaxVarianceAmount] [decimal] (20, 6) NULL,
[CurrencyVarianceAmount] [decimal] (20, 6) NULL,
[InvoiceLevelCharge] [decimal] (20, 6) NULL,
[InvoiceDueDate] [datetime] NULL,
[AlternateInvoiceNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StoreNumber] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerReferenceNumber] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SenderName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SenderCompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SenderAddressLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SenderAddressLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SenderCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SenderState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SenderPostal] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SenderCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverCompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverAddressLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverAddressLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverPostal] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiverCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThirdPartyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThirdPartyCompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThirdPartyAddressLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThirdPartyAddressLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThirdPartyCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThirdPartyState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThirdPartyPostal] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThirdPartyCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldToName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldToCompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldToAddressLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldToAddressLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldToCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldToState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldToPostal] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldToCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddressQual1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress1Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress1CompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress1AddressLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress1AddressLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress1City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress1State] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress1Postal] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress1Country] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddressQual2] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress2Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress2CompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress2AddressLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress2AddressLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress2City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress2State] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress2Postal] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousAddress2Country] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentDate] [datetime] NULL,
[ShipmentExportDate] [datetime] NULL,
[ShipmentImportDate] [datetime] NULL,
[EntryDate] [datetime] NULL,
[DirectShipmentDate] [datetime] NULL,
[ShipmentDeliveryDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentReleaseDate] [datetime] NULL,
[CycleDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFTDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValidationDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntryPort] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntryNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExportPlace] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipmentValueAmount] [decimal] (20, 6) NULL,
[ShipmentDescription] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnteredCurrencyCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomsNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExchangeRate] [decimal] (20, 6) NULL,
[MasterAirWaybillNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EPU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntryType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPCCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineItemNumber] [int] NULL,
[GoodsDescription] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnteredValue] [decimal] (20, 6) NULL,
[DutyAmount] [decimal] (20, 6) NULL,
[Weight] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitOfMeasure] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ItemQuantity] [int] NULL,
[ItemQuantityUnitOfMeasure] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImportTaxId] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeclarationNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCCDNumber] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CycleNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForeignTradeReferenceNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransportMode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxType] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TariffCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TariffRate] [decimal] (20, 6) NULL,
[TariffTreatmentNumber] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocumentType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficeNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocumentNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DutyValue] [decimal] (20, 6) NULL,
[TotalValueForDuty] [decimal] (20, 6) NULL,
[ExciseTaxAmount] [decimal] (20, 6) NULL,
[ExciseTaxRate] [decimal] (20, 6) NULL,
[GSTAmount] [decimal] (20, 6) NULL,
[GSTRate] [decimal] (20, 6) NULL,
[OrderInCouncil] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SIMAAccess] [decimal] (20, 6) NULL,
[TaxValue] [decimal] (20, 6) NULL,
[TotalCustomsAmount] [decimal] (20, 6) NULL,
[MiscellaneousLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayorRoleCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine8] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine9] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine10] [varchar] (58) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiscellaneousLine11] [varchar] (91) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DutyRate] [decimal] (20, 6) NULL,
[VATBasisAmount] [decimal] (20, 6) NULL,
[VATAmount] [decimal] (20, 6) NULL,
[VATRate] [decimal] (20, 6) NULL,
[OtherBasisAmount] [decimal] (20, 6) NULL,
[OtherAmount] [decimal] (20, 6) NULL,
[OtherRate] [decimal] (20, 6) NULL,
[OtherCustomsNumberIndicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherCustomsNumber] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomsOfficeName] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PackageDimensionUnitOfMeasure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalShipmentPackageQuantity] [int] NULL,
[PlaceHolder24] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder25] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder26] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder27] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder28] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder29] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder30] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder31] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOLNumber1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOLNumber2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOLNumber3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOLNumber4] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOLNumber5] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber4] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber5] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber6] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber7] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber8] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber9] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PONumber10] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NMFC] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DetailClass] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FreightSequenceNumber] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeclaredFreightClass] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder34] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder35] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder36] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder37] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder38] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder39] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder40] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder41] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder42] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder43] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder44] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder45] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder46] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder47] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder48] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder49] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder50] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder51] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder52] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder53] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder54] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder55] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder56] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder57] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder58] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceHolder59] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatorCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowCreateDT] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [UPS].[Variance] ADD CONSTRAINT [PK__Variance__3214EC274CADDBCB] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
