copy ..\EDI_iConnect.usp_iConnectAck_Stage_1.sql
copy ..\EDI_iConnect.usp_ShipNotice997_Stage_1.sql
copy ..\EDI2040ic.usp_Stage_1.sql
copy ..\EDI3030ic.usp_Stage_1.sql
copy ..\EDI3040ic.usp_Stage_1.sql
copy ..\EDI3060ic.usp_Stage_1.sql
copy ..\EDI4010.usp_Stage_1.sql
copy ..\EDI5050ic.usp_Stage_1.sql
copy ..\EDIADAC.usp_Stage_1.sql
copy ..\EDIAutoLiv.usp_Stage_1.sql
copy ..\EDIChryslerIC.usp_Stage_1.sql
copy ..\EDIEDIFACT04A.usp_Stage_1.sql
copy ..\EDIEDIFACT97A.usp_Stage_1.sql
copy ..\ediFordic.usp_Stage_1.sql
copy ..\EDILearMexico.usp_Stage_1.sql
copy ..\EDIMagnaITC.usp_Stage_1.sql
copy ..\EDINAL.usp_Stage_1.sql
copy ..\EDIPILOT.usp_Stage_1.sql
copy ..\EDISTANLEY.usp_Stage_1.sql
copy ..\EDIVARROCic.usp_Stage_1.sql
copy ..\FS.usp_XMLShipNotice_CreateOutboundFile.sql
copy ..\FT.usp_EmailFailedFTP.sql
copy ..\FTP.usp_SendCustomerEDI.sql
copy ..\FTP.usp_SendCustomerEDI_TestMailBox.sql