CREATE TABLE [dbo].[RawEDIData] AS FILETABLE ON [PRIMARY] FILESTREAM_ON [FxEDI_FILESTREAM]
WITH
(
	FILETABLE_DIRECTORY = N'RawEDIData', FILETABLE_COLLATE_FILENAME = SQL_Latin1_General_CP1_CI_AS
)
GO
CREATE NONCLUSTERED INDEX [ix_RawEDIData_1] ON [dbo].[RawEDIData] ([is_directory], [name]) ON [PRIMARY]
GO
