//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APInvoices.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APHeaderBarcode
    {
        public string Vendor { get; set; }
        public string InvCMFlag { get; set; }
        public string InvoiceCM { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public int RowID { get; set; }
        public Nullable<System.DateTime> RowCreateDT { get; set; }
        public string RowCreateUser { get; set; }
        public Nullable<System.DateTime> RowModifiedDT { get; set; }
        public string RowModifiedUser { get; set; }
    }
}
