CREATE TABLE [dbo].[Honduras1]
(
[id] [int] NOT NULL,
[company] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[destination] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[destinationName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[destinationAddress1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[destinationAddress2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[destinationAddress3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[destinationAddress4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[customerName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[customerAddress1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerAddress2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerAddress3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerAddress4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[supplier_code] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ShipperAetcNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fob] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[freight_type] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierName] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[note] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_po] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[qty_original] [numeric] (20, 6) NULL,
[qty_packed] [numeric] (20, 6) NULL,
[part] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cross_ref] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[staged_objs] [int] NULL,
[Shipperstaged_pallets] [int] NULL,
[gross_weight] [numeric] (20, 6) NULL,
[note_for_bol] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[note_for_shipper] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[notes] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_shipped] [datetime] NULL,
[customer_part] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bill_of_lading_number] [int] NULL,
[tare_weight] [numeric] (20, 6) NULL,
[net_weight] [numeric] (20, 6) NULL,
[pro_number] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[truck_number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[boxes_staged] [int] NULL,
[prev_cum_in_asn] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accum_shipped] [numeric] (20, 6) NULL,
[consigneeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneeAddress1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneeAddress2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneeAddress3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneeAddress4] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldFromCompany] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SoldFromAddress1] [varchar] (41) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldFromAddress2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldFromAddress3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SoldFromPhone1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trans_mode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[standard_pack] [numeric] (20, 6) NULL,
[standard_unit] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_stamp] [datetime] NULL,
[part_original] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[staged_pallets] [int] NULL,
[CustomerPO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[todaysdate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipping_dock] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[engineering_level] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[terms] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[aetc_number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[our_cum] [numeric] (20, 6) NULL,
[Shipperstaged_objs] [int] NULL,
[shipper_no] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zone_code] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[product_line] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateShipped] [datetime] NULL,
[plant] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[release_no] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASNRequired] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[order_no] [numeric] (8, 0) NULL,
[PlantName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlantAddress1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlantAddress2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlantAddress3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
