CREATE TABLE [dbo].[Corte_InventarioProduccion]
(
[Circuito] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ubicacion] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CantidadCircuito] [int] NULL,
[Tipo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HojaCorte] [bit] NULL,
[Costo] [numeric] (9, 6) NULL,
[Revision] [int] NULL,
[InventarioInicial] [int] NULL,
[TotalFG] [int] NULL,
[TotalPotting] [int] NULL,
[Estacion] [int] NULL,
[Piso] [int] NULL,
[Corte] [int] NULL,
[Ensamble] [int] NULL,
[RebajadoPiso_TransferProcesos] [int] NULL,
[JobCompleteProcesos] [int] NULL,
[TotalInventarioFisico] [int] NULL,
[SubTotal] [int] NULL,
[Total] [int] NULL,
[AcumD1] [int] NULL,
[AcumD2] [int] NULL,
[AcumD3] [int] NULL,
[AcumD4] [int] NULL,
[AcumD5] [int] NULL,
[AcumD6] [int] NULL,
[ReleaseDiario] [int] NULL,
[TotalDiario] [int] NULL,
[Desface] [int] NULL,
[Color] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TipoInventario] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTTransaction] [datetime] NULL,
[RechazoCorte] [int] NULL,
[Contencion] [int] NULL
) ON [PRIMARY]
GO
