CREATE TABLE [FT].[CSM_VendorSpend]
(
[base_part] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[program] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[manufacturer] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[badge] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CSM_eop_display] [datetime] NULL,
[CSM_sop_display] [datetime] NULL,
[FGDemand2016] [numeric] (38, 6) NULL,
[FGDemand2017] [numeric] (38, 6) NULL,
[FGDemand2018] [numeric] (38, 6) NULL,
[FGDemand2019] [numeric] (38, 6) NULL,
[FGDemand2020] [numeric] (38, 6) NULL,
[FGDemand2021] [numeric] (38, 6) NULL,
[FGDemand2022] [numeric] (38, 6) NULL,
[FGDemand2023] [numeric] (38, 6) NULL,
[FGDemand2024] [numeric] (38, 6) NULL,
[FGDemand2025] [numeric] (38, 6) NULL,
[RawPart] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Commodity] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QtyPer] [numeric] (20, 6) NULL,
[RawPartDemand2016] [numeric] (38, 6) NULL,
[RawPartDemand2017] [numeric] (38, 6) NULL,
[RawPartDemand2018] [numeric] (38, 6) NULL,
[RawPartDemand2019] [numeric] (38, 6) NULL,
[RawPartDemand2020] [numeric] (38, 6) NULL,
[RawPartDemand2021] [numeric] (38, 6) NULL,
[RawPartDemand2022] [numeric] (38, 6) NULL,
[RawPartDemand2023] [numeric] (38, 6) NULL,
[RawPartDemand2024] [numeric] (38, 6) NULL,
[RawPartDemand2025] [numeric] (38, 6) NULL,
[RawPartSpend2016] [numeric] (38, 6) NULL,
[RawPartSpend2017] [numeric] (38, 6) NULL,
[RawPartSpend2018] [numeric] (38, 6) NULL,
[RawPartSpend2019] [numeric] (38, 6) NULL,
[RawPartSpend2020] [numeric] (38, 6) NULL,
[RawPartSpend2021] [numeric] (38, 6) NULL,
[RawPartSpend2022] [numeric] (38, 6) NULL,
[RawPartSpend2023] [numeric] (38, 6) NULL,
[RawPartSpend2024] [numeric] (38, 6) NULL,
[RawPartSpend2025] [numeric] (38, 6) NULL,
[default_vendor] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[standard_pack] [numeric] (20, 6) NULL,
[HTSCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HTSDescription] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HTSCountry] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HTSType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartInventoryCountryName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POShipTo] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadTime] [numeric] (22, 8) NULL,
[StandardCost] [numeric] (20, 6) NULL,
[LeadTimeFlag] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MaxCSMEOPforRawPart] [datetime] NULL,
[MinCSMSOPforRawPart] [datetime] NULL,
[AllRawPartInventory] [numeric] (38, 6) NULL,
[VendorTerms] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TariffName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TariffRate] [numeric] (18, 4) NULL,
[TariffEffectiveDate] [datetime] NULL,
[RelatedTariffList] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TariffImposingCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
