USE [MONITOR]
GO

/****** Object:  Table [EEIUser].[QT_Requote]    Script Date: 03/04/2013 11:42:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [EEIUser].[QT_Requote](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Type] [char](2) NOT NULL,
	[Description] [varchar](50) NULL,
 CONSTRAINT [PK__Requote__3214EC277617DDD5] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

