//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FxFTP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingRDPDateRange
    {
        public System.DateTime FromDT { get; set; }
        public System.DateTime ToDT { get; set; }
        public long RowID { get; set; }
    }
}
