//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FxFTP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskActivity
    {
        public string TaskName { get; set; }
        public string LastRunOutcome { get; set; }
        public Nullable<System.DateTime> LastRun { get; set; }
        public Nullable<System.DateTime> NextRun { get; set; }
        public int RowID { get; set; }
    }
}
