CREATE USER [ASPNET] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[ASPNET]
GO
GRANT BACKUP DATABASE TO [ASPNET]
GRANT CREATE DEFAULT TO [ASPNET]
GRANT CREATE FUNCTION TO [ASPNET]
GRANT CREATE PROCEDURE TO [ASPNET]
GRANT CREATE RULE TO [ASPNET]
GRANT CREATE TABLE TO [ASPNET]
GRANT CREATE VIEW TO [ASPNET]
