IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'EMPIREELECT\dan')
CREATE LOGIN [EMPIREELECT\dan] FROM WINDOWS
GO
CREATE USER [EMPIREELECT\dan] FOR LOGIN [EMPIREELECT\dan]
GO
