IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'EMPIRE\HChavez')
CREATE LOGIN [EMPIRE\HChavez] FROM WINDOWS
GO
CREATE USER [EMPIRE\HChaves] FOR LOGIN [EMPIRE\HChavez] WITH DEFAULT_SCHEMA=[EMPIRE\HChaves]
GO
REVOKE CONNECT TO [EMPIRE\HChaves]
