IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'EMPIREELECT\EEI_EMPOWER_USERS')
CREATE LOGIN [EMPIREELECT\EEI_EMPOWER_USERS] FROM WINDOWS
GO
CREATE USER [EMPIREELECT\EEI_EMPOWER_USERS] FOR LOGIN [EMPIREELECT\EEI_EMPOWER_USERS]
GO
