IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'EMPIREELECT\eeiship')
CREATE LOGIN [EMPIREELECT\eeiship] FROM WINDOWS
GO
CREATE USER [EMPIREELECT\eeiship] FOR LOGIN [EMPIREELECT\eeiship] WITH DEFAULT_SCHEMA=[EMPIREELECT\eeiship]
GO
REVOKE CONNECT TO [EMPIREELECT\eeiship]
