IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'EMPIREELECT\jstoehr')
CREATE LOGIN [EMPIREELECT\jstoehr] FROM WINDOWS
GO
CREATE USER [EMPIREELECT\jstoehr] FOR LOGIN [EMPIREELECT\jstoehr] WITH DEFAULT_SCHEMA=[EMPIREELECT\jstoehr]
GO
REVOKE CONNECT TO [EMPIREELECT\jstoehr]
