//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Areas.PartVendorQuotes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MONITOREntities4 : DbContext
    {
        public MONITOREntities4()
            : base("name=MONITOREntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<usp_GetParts_Result> usp_GetParts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetParts_Result>("usp_GetParts");
        }
    
        public virtual ObjectResult<usp_GetVendors_Result> usp_GetVendors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetVendors_Result>("usp_GetVendors");
        }
    
        public virtual ObjectResult<usp_GetOems_Result> usp_GetOems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOems_Result>("usp_GetOems");
        }
    
        public virtual int usp_AddPartVendorQuote(string user, string vendorCode, string partCode, string oem, Nullable<System.DateTime> effectiveDate, Nullable<System.DateTime> endDate, Nullable<decimal> price, ObjectParameter tranDT, ObjectParameter result, Nullable<int> debug, ObjectParameter debugMsg)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var vendorCodeParameter = vendorCode != null ?
                new ObjectParameter("VendorCode", vendorCode) :
                new ObjectParameter("VendorCode", typeof(string));
    
            var partCodeParameter = partCode != null ?
                new ObjectParameter("PartCode", partCode) :
                new ObjectParameter("PartCode", typeof(string));
    
            var oemParameter = oem != null ?
                new ObjectParameter("Oem", oem) :
                new ObjectParameter("Oem", typeof(string));
    
            var effectiveDateParameter = effectiveDate.HasValue ?
                new ObjectParameter("EffectiveDate", effectiveDate) :
                new ObjectParameter("EffectiveDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var debugParameter = debug.HasValue ?
                new ObjectParameter("Debug", debug) :
                new ObjectParameter("Debug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AddPartVendorQuote", userParameter, vendorCodeParameter, partCodeParameter, oemParameter, effectiveDateParameter, endDateParameter, priceParameter, tranDT, result, debugParameter, debugMsg);
        }
    
        public virtual ObjectResult<usp_GetPartVendorQuotes_Result> usp_GetPartVendorQuotes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetPartVendorQuotes_Result>("usp_GetPartVendorQuotes");
        }
    
        public virtual int usp_EditPartVendorQuote(string user, Nullable<int> rowID, string vendorCode, string partCode, string oem, Nullable<System.DateTime> effectiveDate, Nullable<System.DateTime> endDate, Nullable<decimal> price, ObjectParameter tranDT, ObjectParameter result, Nullable<int> debug, ObjectParameter debugMsg)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var rowIDParameter = rowID.HasValue ?
                new ObjectParameter("RowID", rowID) :
                new ObjectParameter("RowID", typeof(int));
    
            var vendorCodeParameter = vendorCode != null ?
                new ObjectParameter("VendorCode", vendorCode) :
                new ObjectParameter("VendorCode", typeof(string));
    
            var partCodeParameter = partCode != null ?
                new ObjectParameter("PartCode", partCode) :
                new ObjectParameter("PartCode", typeof(string));
    
            var oemParameter = oem != null ?
                new ObjectParameter("Oem", oem) :
                new ObjectParameter("Oem", typeof(string));
    
            var effectiveDateParameter = effectiveDate.HasValue ?
                new ObjectParameter("EffectiveDate", effectiveDate) :
                new ObjectParameter("EffectiveDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var debugParameter = debug.HasValue ?
                new ObjectParameter("Debug", debug) :
                new ObjectParameter("Debug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EditPartVendorQuote", userParameter, rowIDParameter, vendorCodeParameter, partCodeParameter, oemParameter, effectiveDateParameter, endDateParameter, priceParameter, tranDT, result, debugParameter, debugMsg);
        }
    
        public virtual ObjectResult<usp_PVQ_FileManagement_Get_Result> usp_PVQ_FileManagement_Get(string quoteNumber, string attachmentCategory, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var attachmentCategoryParameter = attachmentCategory != null ?
                new ObjectParameter("AttachmentCategory", attachmentCategory) :
                new ObjectParameter("AttachmentCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PVQ_FileManagement_Get_Result>("usp_PVQ_FileManagement_Get", quoteNumberParameter, attachmentCategoryParameter, tranDT, result);
        }
    
        public virtual int usp_PVQ_FileManagement_Save(string quoteNumber, string attachmentCategory, string fileName, byte[] fileContents, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var attachmentCategoryParameter = attachmentCategory != null ?
                new ObjectParameter("AttachmentCategory", attachmentCategory) :
                new ObjectParameter("AttachmentCategory", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var fileContentsParameter = fileContents != null ?
                new ObjectParameter("FileContents", fileContents) :
                new ObjectParameter("FileContents", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_PVQ_FileManagement_Save", quoteNumberParameter, attachmentCategoryParameter, fileNameParameter, fileContentsParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_DeletePartVendorQuote_Result> usp_DeletePartVendorQuote(string user, Nullable<int> rowID, string attachmentCategory, ObjectParameter tranDT, ObjectParameter result, Nullable<int> debug, ObjectParameter debugMsg)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            var rowIDParameter = rowID.HasValue ?
                new ObjectParameter("RowID", rowID) :
                new ObjectParameter("RowID", typeof(int));
    
            var attachmentCategoryParameter = attachmentCategory != null ?
                new ObjectParameter("AttachmentCategory", attachmentCategory) :
                new ObjectParameter("AttachmentCategory", typeof(string));
    
            var debugParameter = debug.HasValue ?
                new ObjectParameter("Debug", debug) :
                new ObjectParameter("Debug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DeletePartVendorQuote_Result>("usp_DeletePartVendorQuote", userParameter, rowIDParameter, attachmentCategoryParameter, tranDT, result, debugParameter, debugMsg);
        }
    
        public virtual ObjectResult<usp_PVQ_FileManagement_Delete_Result> usp_PVQ_FileManagement_Delete(string quoteNumber, string attachmentCategory, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var attachmentCategoryParameter = attachmentCategory != null ?
                new ObjectParameter("AttachmentCategory", attachmentCategory) :
                new ObjectParameter("AttachmentCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PVQ_FileManagement_Delete_Result>("usp_PVQ_FileManagement_Delete", quoteNumberParameter, attachmentCategoryParameter, tranDT, result);
        }
    }
}
