CREATE TABLE [CRC32].[IndexTable]
(
[Id] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [CRC32].[IndexTable] ADD CONSTRAINT [PK__IndexTab__3214EC070667919C] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
