//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierEDI.Web.SupplierEDIModule.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SupplierEDI_Entities : DbContext
    {
        public SupplierEDI_Entities()
            : base("name=SupplierEDI_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<XML_ReleasePlanDataRootFunctions> XML_ReleasePlanDataRootFunctions { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<TradingPartnerOverlayGroup> TradingPartnerOverlayGroups { get; set; }
    
        public virtual ObjectResult<usp_GetPurchaseOrderList_Result> usp_GetPurchaseOrderList(ObjectParameter tranDT, ObjectParameter result, Nullable<int> debug, ObjectParameter debugMsg)
        {
            var debugParameter = debug.HasValue ?
                new ObjectParameter("Debug", debug) :
                new ObjectParameter("Debug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetPurchaseOrderList_Result>("usp_GetPurchaseOrderList", tranDT, result, debugParameter, debugMsg);
        }
    
        public virtual int usp_Get830XML(string tradingPartnerCode, string purchaseOrderList, string xMLGet830_FunctionName, string purposeCode, Nullable<bool> complete, ObjectParameter xML830, ObjectParameter tranDT, ObjectParameter result, Nullable<int> debug, ObjectParameter debugMsg)
        {
            var tradingPartnerCodeParameter = tradingPartnerCode != null ?
                new ObjectParameter("TradingPartnerCode", tradingPartnerCode) :
                new ObjectParameter("TradingPartnerCode", typeof(string));
    
            var purchaseOrderListParameter = purchaseOrderList != null ?
                new ObjectParameter("PurchaseOrderList", purchaseOrderList) :
                new ObjectParameter("PurchaseOrderList", typeof(string));
    
            var xMLGet830_FunctionNameParameter = xMLGet830_FunctionName != null ?
                new ObjectParameter("XMLGet830_FunctionName", xMLGet830_FunctionName) :
                new ObjectParameter("XMLGet830_FunctionName", typeof(string));
    
            var purposeCodeParameter = purposeCode != null ?
                new ObjectParameter("PurposeCode", purposeCode) :
                new ObjectParameter("PurposeCode", typeof(string));
    
            var completeParameter = complete.HasValue ?
                new ObjectParameter("Complete", complete) :
                new ObjectParameter("Complete", typeof(bool));
    
            var debugParameter = debug.HasValue ?
                new ObjectParameter("Debug", debug) :
                new ObjectParameter("Debug", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Get830XML", tradingPartnerCodeParameter, purchaseOrderListParameter, xMLGet830_FunctionNameParameter, purposeCodeParameter, completeParameter, xML830, tranDT, result, debugParameter, debugMsg);
        }
    }
}
