//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmaMaintenance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HondurasLocation
    {
        public string LocationCode { get; set; }
        public int IsStorage { get; set; }
        public int IsSecure { get; set; }
    }
}
