//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmaMaintenance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenRTV
    {
        public int RTVShipper { get; set; }
        public Nullable<bool> PackingSlipPrinted { get; set; }
        public string HN_RMA_Location { get; set; }
        public string ProductLine { get; set; }
        public string SerialList { get; set; }
    }
}
