//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmaMaintenance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialsQuantitiesToAutoRMA_RTV
    {
        public int Serial { get; set; }
        public decimal Quantity { get; set; }
        public string OperatorCode { get; set; }
    }
}
