copy ..\FT.usp_EmailFailedFTP.sql
copy ..\FT.ftsp_InventoryGenesis_LoadEEI_Explotion.sql
copy ..\EEIUser.usp_Quoting_DeleteAttachment.sql
copy ..\EEIUser.OBS_acctg_intercompany_reconcile_update_transfer_pricing_to_prior_month.sql
copy ..\EEIUser.usp_Quoting_SaveAttachment.sql
copy ..\dbo.vwft_ActivePartMaterialAccum.sql
copy ..\EEIUser.acctg_intercompany_reconcile_update_transfer_pricing.sql
copy ..\EDI.usp_CustomerEDI_SendShipNotices.sql
copy ..\dbo.eeisp_rpt_object_historical.sql
copy ..\dbo.SSR_PutSerialOnHold.sql
copy ..\EEIUser.usp_Quoting_GetAttachment.sql
copy ..\EEIUser.OBS_SP_Intercompany_Reconciliation.sql
copy ..\FT.ftsp_InventoryGenesis_LoadEEI.sql
copy ..\EEIUser.acctg_cost_of_goods_sold.sql