SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[VW_Month] AS

	SELECT ID = 0 UNION ALL 
	SELECT ID = 1 UNION ALL 
	SELECT ID = 2 UNION ALL 
	SELECT ID = 3 UNION ALL 
	SELECT ID = 4 UNION ALL 
	SELECT ID = 5 UNION ALL 
	SELECT ID = 6 UNION ALL 
	SELECT ID = 7 UNION ALL 
	SELECT ID = 8 UNION ALL 
	SELECT ID = 9 UNION ALL 
	SELECT ID = 10 UNION ALL 
	SELECT ID = 11 UNION ALL 
	SELECT ID = 12 
	

GO
GRANT ALTER ON  [dbo].[VW_Month] TO [public]
GO
GRANT SELECT ON  [dbo].[VW_Month] TO [public]
GO
GRANT VIEW DEFINITION ON  [dbo].[VW_Month] TO [public]
GO
