IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'EMPIREELECT\CDiPaola')
CREATE LOGIN [EMPIREELECT\CDiPaola] FROM WINDOWS
GO
CREATE USER [EMPIREELECT\CDiPaola] FOR LOGIN [EMPIREELECT\CDiPaola]
GO
