//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteLogData.Models
{
    using System;
    
    public partial class CompletedQuotes
    {
        public Nullable<int> OnTime { get; set; }
        public Nullable<int> Late { get; set; }
        public string X { get { return DateTime.Today.Year.ToString(); } }
    }
}
