//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteLogData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSM_Mnemonic
    {
        public string Release_ID { get; set; }
        public string Version { get; set; }
        public string Mnemonic_Vehicle { get; set; }
        public string Mnemonic_Vehicle_Plant { get; set; }
        public string Mnemonic_Platform { get; set; }
        public string Region { get; set; }
        public string Market { get; set; }
        public string Country { get; set; }
        public string Plant { get; set; }
        public string City { get; set; }
        public string Plant_State_Province { get; set; }
        public string Source_Plant { get; set; }
        public string Source_Country { get; set; }
        public string Source_Region { get; set; }
        public string Design_Parent { get; set; }
        public string Engineering_Group { get; set; }
        public string Manufacturing_Group { get; set; }
        public string Manufacturer { get; set; }
        public string Sales_Parent { get; set; }
        public string Brand { get; set; }
        public string Platform_Design_Owner { get; set; }
        public string Architecture { get; set; }
        public string Platform { get; set; }
        public string Program { get; set; }
        public string Nameplate { get; set; }
        public Nullable<System.DateTime> SOP { get; set; }
        public Nullable<System.DateTime> EOP { get; set; }
        public Nullable<int> Lifecycle__Time_ { get; set; }
        public string Vehicle { get; set; }
        public string Assembly_Type { get; set; }
        public string Strategic_Group { get; set; }
        public string Sales_Group { get; set; }
        public string Global_Nameplate { get; set; }
        public Nullable<decimal> EAU { get; set; }
        public Nullable<decimal> CY_2012 { get; set; }
        public Nullable<decimal> CY_2013 { get; set; }
        public Nullable<decimal> CY_2014 { get; set; }
        public Nullable<decimal> CY_2015 { get; set; }
        public Nullable<decimal> CY_2016 { get; set; }
        public Nullable<decimal> CY_2017 { get; set; }
        public Nullable<decimal> CY_2018 { get; set; }
        public Nullable<decimal> CY_2019 { get; set; }
    }
}
