//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteLogData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteTreeList
    {
        public int RowID { get; set; }
        public string QuoteNumber { get; set; }
        public Nullable<int> ParentQuoteID { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Customer { get; set; }
        public string EEIPartNumber { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<decimal> QuotePrice { get; set; }
        public string Notes { get; set; }
    }
}
