//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoteLogData.Models
{
    using System;
    
    public partial class TopCustomersBySales
    {
        public string Customer { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
    }
}
