//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.QuoteLogIntegration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MONITOREntitiesQuoteLogIntegrationQuoteTransfer : DbContext
    {
        public MONITOREntitiesQuoteLogIntegrationQuoteTransfer()
            : base("name=MONITOREntitiesQuoteLogIntegrationQuoteTransfer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<usp_QL_QuoteTransfer_GetDocumentation_Result> usp_QL_QuoteTransfer_GetDocumentation(string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QL_QuoteTransfer_GetDocumentation_Result>("usp_QL_QuoteTransfer_GetDocumentation", quoteNumberParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_QL_QuoteTransfer_GetQuote_Result> usp_QL_QuoteTransfer_GetQuote(string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QL_QuoteTransfer_GetQuote_Result>("usp_QL_QuoteTransfer_GetQuote", quoteNumberParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_ToolingBreakdown_Insert(string operatorCode, string quoteNumber, string description, Nullable<int> quantity, Nullable<decimal> value, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var valueParameter = value.HasValue ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_ToolingBreakdown_Insert", operatorCodeParameter, quoteNumberParameter, descriptionParameter, quantityParameter, valueParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_ToolingBreakdown_Update(string operatorCode, Nullable<int> id, string description, Nullable<int> quantity, Nullable<decimal> value, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var valueParameter = value.HasValue ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_ToolingBreakdown_Update", operatorCodeParameter, idParameter, descriptionParameter, quantityParameter, valueParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_ToolingBreakdown_Delete(string operatorCode, Nullable<int> id, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_ToolingBreakdown_Delete", operatorCodeParameter, idParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_CustomerContacts_Insert(string operatorCode, string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_CustomerContacts_Insert", operatorCodeParameter, quoteNumberParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_CustomerContacts_Update(string operatorCode, Nullable<int> id, string firstName, string lastName, string phoneNumber, string faxNumber, string emailAddress, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var faxNumberParameter = faxNumber != null ?
                new ObjectParameter("FaxNumber", faxNumber) :
                new ObjectParameter("FaxNumber", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_CustomerContacts_Update", operatorCodeParameter, idParameter, firstNameParameter, lastNameParameter, phoneNumberParameter, faxNumberParameter, emailAddressParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_QL_QuoteTransfer_GetCustomerContacts_Result> usp_QL_QuoteTransfer_GetCustomerContacts(string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QL_QuoteTransfer_GetCustomerContacts_Result>("usp_QL_QuoteTransfer_GetCustomerContacts", quoteNumberParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_SpecialReqNotes_Insert(string operatorCode, string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_SpecialReqNotes_Insert", operatorCodeParameter, quoteNumberParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_SpecialReqNotes_Update(string operatorCode, Nullable<int> id, string answer, string notes, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var answerParameter = answer != null ?
                new ObjectParameter("Answer", answer) :
                new ObjectParameter("Answer", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_SpecialReqNotes_Update", operatorCodeParameter, idParameter, answerParameter, notesParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_QL_QuoteTransfer_GetSpecialReqNotes_Result> usp_QL_QuoteTransfer_GetSpecialReqNotes(string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QL_QuoteTransfer_GetSpecialReqNotes_Result>("usp_QL_QuoteTransfer_GetSpecialReqNotes", quoteNumberParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_QT_FileManagement_Delete_Result> usp_QT_FileManagement_Delete(string quoteNumber, string attachmentCategory, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var attachmentCategoryParameter = attachmentCategory != null ?
                new ObjectParameter("AttachmentCategory", attachmentCategory) :
                new ObjectParameter("AttachmentCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QT_FileManagement_Delete_Result>("usp_QT_FileManagement_Delete", quoteNumberParameter, attachmentCategoryParameter, tranDT, result);
        }
    
        public virtual int usp_QT_FileManagement_Save(string quoteNumber, string attachmentCategory, string fileName, byte[] fileContents, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var attachmentCategoryParameter = attachmentCategory != null ?
                new ObjectParameter("AttachmentCategory", attachmentCategory) :
                new ObjectParameter("AttachmentCategory", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var fileContentsParameter = fileContents != null ?
                new ObjectParameter("FileContents", fileContents) :
                new ObjectParameter("FileContents", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QT_FileManagement_Save", quoteNumberParameter, attachmentCategoryParameter, fileNameParameter, fileContentsParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_QT_FileManagement_Get_Result> usp_QT_FileManagement_Get(string quoteNumber, string attachmentCategory, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var attachmentCategoryParameter = attachmentCategory != null ?
                new ObjectParameter("AttachmentCategory", attachmentCategory) :
                new ObjectParameter("AttachmentCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QT_FileManagement_Get_Result>("usp_QT_FileManagement_Get", quoteNumberParameter, attachmentCategoryParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_QL_QuoteTransfer_GetSignOffInitials_Result> usp_QL_QuoteTransfer_GetSignOffInitials(string type, ObjectParameter tranDT, ObjectParameter result)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QL_QuoteTransfer_GetSignOffInitials_Result>("usp_QL_QuoteTransfer_GetSignOffInitials", typeParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_QL_QuoteTransfer_GetSignOff_Result> usp_QL_QuoteTransfer_GetSignOff(string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QL_QuoteTransfer_GetSignOff_Result>("usp_QL_QuoteTransfer_GetSignOff", quoteNumberParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_SignOff_Insert(string operatorCode, string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_SignOff_Insert", operatorCodeParameter, quoteNumberParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_SignOff_Update(string operatorCode, Nullable<int> id, string initials, Nullable<System.DateTime> signOffDate, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var initialsParameter = initials != null ?
                new ObjectParameter("Initials", initials) :
                new ObjectParameter("Initials", typeof(string));
    
            var signOffDateParameter = signOffDate.HasValue ?
                new ObjectParameter("SignOffDate", signOffDate) :
                new ObjectParameter("SignOffDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_SignOff_Update", operatorCodeParameter, idParameter, initialsParameter, signOffDateParameter, tranDT, result);
        }
    
        public virtual ObjectResult<usp_QL_QuoteTransfer_GetToolingBreakdown_Result> usp_QL_QuoteTransfer_GetToolingBreakdown(string quoteNumber, ObjectParameter tranDT, ObjectParameter result)
        {
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_QL_QuoteTransfer_GetToolingBreakdown_Result>("usp_QL_QuoteTransfer_GetToolingBreakdown", quoteNumberParameter, tranDT, result);
        }
    
        public virtual int usp_QL_QuoteTransfer_Documentation_Insert(string operatorCode, string quoteNumber, string description, string answer, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var quoteNumberParameter = quoteNumber != null ?
                new ObjectParameter("QuoteNumber", quoteNumber) :
                new ObjectParameter("QuoteNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var answerParameter = answer != null ?
                new ObjectParameter("Answer", answer) :
                new ObjectParameter("Answer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_QL_QuoteTransfer_Documentation_Insert", operatorCodeParameter, quoteNumberParameter, descriptionParameter, answerParameter, tranDT, result);
        }
    }
}
