SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[EEHSP_Run_Ars_fxDelete] AS

BEGIN TRANSACTION
	EXEC FT.ftsp_RebuildXRt
COMMIT TRANSACTION

BEGIN TRANSACTION
	EXEC FT.csp_AutoPOGennoXRtRebuild
COMMIT TRANSACTION
GO
