SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create procedure [dbo].[EEIsp_ConvertCSMRawForecast] 
as
Begin
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/01/01',
				Sales1
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/02/01',
				Sales2
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/03/01',
				Sales3
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/04/01',
				Sales4
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/05/01',
				Sales5
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/06/01',
				Sales6
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/07/01',
				Sales7
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/08/01',
				Sales8
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/09/01',
				Sales9
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/10/01',
				Sales10
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/11/01',
				Sales11
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/12/01',
				Sales12
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/01/01',
				Sales13
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	

	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/02/01',
				Sales14
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/03/01',
				Sales15
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/04/01',
				Sales16
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/05/01',
				Sales17
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/06/01',
				Sales18
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/07/01',
				Sales19
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/08/01',
				Sales20
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/09/01',
				Sales21
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/10/01',
				Sales22
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/11/01',
				Sales23
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2005/12/01',
				Sales24
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/01/01',
				Sales25
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/02/01',
				Sales26
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/03/01',
				Sales27
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/04/01',
				Sales28
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/05/01',
				Sales29
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/06/01',
				Sales30
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/07/01',
				Sales31
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/08/01',
				Sales32
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/09/01',
				Sales33
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/10/01',
				Sales34
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/11/01',
				Sales35
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2006/12/01',
				Sales36
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/01/01',
				Sales37
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/02/01',
				Sales38
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/03/01',
				Sales39
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/04/01',
				Sales40
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/05/01',
				Sales41
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/06/01',
				Sales42
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/07/01',
				Sales43
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/08/01',
				Sales44
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/09/01',
				Sales45
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/10/01',
				Sales46
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2004/11/01',
				Sales47
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2007/12/01',
				Sales48
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2008/01/01',
				Sales49
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2008/04/01',
				Sales50
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2008/07/01',
				Sales51
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2008/10/01',
				Sales52
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2009/01/01',
				Sales53
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2009/04/01',
				Sales54
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2009/07/01',
				Sales55
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2009/10/01',
				Sales56
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2010/01/01',
				Sales57
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2010/04/01',
				Sales58
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2010/07/01',
				Sales59
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2010/10/01',
				Sales60
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2011/01/01',
				Sales61
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2011/04/01',
				Sales62
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2011/07/01',
				Sales63
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
	Insert	csmMnemonicSales
	Select	ForecastMonth,
				Mnemonic,
				MnemonicPlatform,
				DesignParent,
				Manufacturer,
				salesParent,
				nameplate,
				badge,
				Architecture,
				program,
				platform,
				ProductType,
				GlobalSegment,
				GlobalSubSegment,
				RegionalSegment,
				sop,
				eop,
				AssemblyPlant,
				AssemblyType,
				SourcePlant,
				SorcePlantCountry,
				countryofassembly,
				market	,
				Region	,
				'2011/10/01',
				Sales64
	from		csmMnemonicSalesraw
	where	ForecastMonth = '62005'
	
End

--08/25/2005 Andre S. Boulanger -  Add ReceiptAuthDays to Part Vendor. This column will be used by the RF receiving application ( csp_RF_CheckQuantity). Also made change to this Procedure and applied on 8/25/05.
GO
