//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCSM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MONITOREntitiesTest : DbContext
    {
        public MONITOREntitiesTest()
            : base("name=MONITOREntitiesTest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int acctg_csm_sp_insert_detail(string operatorCode, string currentRelease, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_insert_detail", operatorCodeParameter, currentReleaseParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_insert_header(string operatorCode, string currentRelease, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_insert_header", operatorCodeParameter, currentReleaseParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_rollforward_detail(string operatorCode, string currentRelease, string priorRelease, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            var priorReleaseParameter = priorRelease != null ?
                new ObjectParameter("PriorRelease", priorRelease) :
                new ObjectParameter("PriorRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_rollforward_detail", operatorCodeParameter, currentReleaseParameter, priorReleaseParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_rollforward_header(string operatorCode, string currentRelease, string priorRelease, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            var priorReleaseParameter = priorRelease != null ?
                new ObjectParameter("PriorRelease", priorRelease) :
                new ObjectParameter("PriorRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_rollforward_header", operatorCodeParameter, currentReleaseParameter, priorReleaseParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_validate_release(string operatorCode, string currentRelease, string region, ObjectParameter message, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_validate_release", operatorCodeParameter, currentReleaseParameter, regionParameter, message, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_import_NA(string operatorCode, string currentRelease, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_import_NA", operatorCodeParameter, currentReleaseParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_import_GC(string operatorCode, string currentRelease, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_import_GC", operatorCodeParameter, currentReleaseParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_check_datecolumns(string operatorCode, string currentRelease, ObjectParameter message, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_check_datecolumns", operatorCodeParameter, currentReleaseParameter, message, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_validate_operator(string operatorCode, ObjectParameter operatorName, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_validate_operator", operatorCodeParameter, operatorName, tranDT, result);
        }
    }
}
