//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCSM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MONITOREntities : DbContext
    {
        public MONITOREntities()
            : base("name=MONITOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int acctg_csm_sp_roll_forward_CSM_data_one_month(string prior_release_id, string current_release_id, ObjectParameter tranDT, ObjectParameter result)
        {
            var prior_release_idParameter = prior_release_id != null ?
                new ObjectParameter("prior_release_id", prior_release_id) :
                new ObjectParameter("prior_release_id", typeof(string));
    
            var current_release_idParameter = current_release_id != null ?
                new ObjectParameter("current_release_id", current_release_id) :
                new ObjectParameter("current_release_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_roll_forward_CSM_data_one_month", prior_release_idParameter, current_release_idParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_import_CSM_demand(string release_ID, string version, ObjectParameter tranDT, ObjectParameter result)
        {
            var release_IDParameter = release_ID != null ?
                new ObjectParameter("Release_ID", release_ID) :
                new ObjectParameter("Release_ID", typeof(string));
    
            var versionParameter = version != null ?
                new ObjectParameter("Version", version) :
                new ObjectParameter("Version", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_import_CSM_demand", release_IDParameter, versionParameter, tranDT, result);
        }
    
        public virtual int acctg_sales_sp_insert_historical_sales(string forecast_name, Nullable<System.DateTime> time_stamp, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> throughDate)
        {
            var forecast_nameParameter = forecast_name != null ?
                new ObjectParameter("forecast_name", forecast_name) :
                new ObjectParameter("forecast_name", typeof(string));
    
            var time_stampParameter = time_stamp.HasValue ?
                new ObjectParameter("time_stamp", time_stamp) :
                new ObjectParameter("time_stamp", typeof(System.DateTime));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var throughDateParameter = throughDate.HasValue ?
                new ObjectParameter("throughDate", throughDate) :
                new ObjectParameter("throughDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_sales_sp_insert_historical_sales", forecast_nameParameter, time_stampParameter, fromDateParameter, throughDateParameter);
        }
    
        public virtual int acctg_sales_sp_insert_official_forecast(string forecast_name, Nullable<System.DateTime> time_stamp)
        {
            var forecast_nameParameter = forecast_name != null ?
                new ObjectParameter("forecast_name", forecast_name) :
                new ObjectParameter("forecast_name", typeof(string));
    
            var time_stampParameter = time_stamp.HasValue ?
                new ObjectParameter("time_stamp", time_stamp) :
                new ObjectParameter("time_stamp", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_sales_sp_insert_official_forecast", forecast_nameParameter, time_stampParameter);
        }
    
        public virtual int acctg_csm_sp_roll_forward_EmpireForecast_data_one_year_fall_off(string prior_release_id, string current_release_id, ObjectParameter tranDT, ObjectParameter result)
        {
            var prior_release_idParameter = prior_release_id != null ?
                new ObjectParameter("prior_release_id", prior_release_id) :
                new ObjectParameter("prior_release_id", typeof(string));
    
            var current_release_idParameter = current_release_id != null ?
                new ObjectParameter("current_release_id", current_release_id) :
                new ObjectParameter("current_release_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_roll_forward_EmpireForecast_data_one_year_fall_off", prior_release_idParameter, current_release_idParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_check_datecolumns(string operatorCode, string currentRelease, ObjectParameter message, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_check_datecolumns", operatorCodeParameter, currentReleaseParameter, message, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_import_GC(string operatorCode, string currentRelease, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_import_GC", operatorCodeParameter, currentReleaseParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_import_NA(string operatorCode, string currentRelease, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_import_NA", operatorCodeParameter, currentReleaseParameter, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_validate_operator(string operatorCode, ObjectParameter operatorName, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_validate_operator", operatorCodeParameter, operatorName, tranDT, result);
        }
    
        public virtual int acctg_csm_sp_validate_release(string operatorCode, string currentRelease, string region, ObjectParameter message, ObjectParameter tranDT, ObjectParameter result)
        {
            var operatorCodeParameter = operatorCode != null ?
                new ObjectParameter("OperatorCode", operatorCode) :
                new ObjectParameter("OperatorCode", typeof(string));
    
            var currentReleaseParameter = currentRelease != null ?
                new ObjectParameter("CurrentRelease", currentRelease) :
                new ObjectParameter("CurrentRelease", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("Region", region) :
                new ObjectParameter("Region", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("acctg_csm_sp_validate_release", operatorCodeParameter, currentReleaseParameter, regionParameter, message, tranDT, result);
        }
    }
}
